/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chandan' at '8/24/16 5:50 PM' with Gradle 2.10
 *
 * @author chandan, @date 8/24/16 5:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
